### ISSUE TITLE
Micro minimosd v2

### ISSUE THREAD

**Issue by Freakshowdevil** [gc9n/rx5808-Diversity-RealAcc-Compatible#11]
Can't get it to work with this one http://buzzhobbies.com.au/index.php?route=product/product&product_id=1094

![micro minim v2 pinout-900x900](https://cloud.githubusercontent.com/assets/21226587/21579841/3861e444-cfc6-11e6-88eb-b4e26c161415.jpg)

**Comment by gc9n** [comment]
Happy new year!
I used the microminim osd from banggood, this the v2 i guess,

**Comment by gc9n** [comment]
tell me what exactly happen.
i remember we make it work right? now whats wrong?

**Comment by gc9n** [comment]
Upload the fonts from my repository with mwosd

**Comment by Freakshowdevil** [comment]
Yeah I'am doing that, but with no luck. its like fonts will not be stored

**Comment by Freakshowdevil** [comment]
Now OSD menu, fatshark buttons, Rssi working, but no vbat is showing only the small goggles no battery. Don't now what was the problem but flashed every thing again.

**Comment by gc9n** [comment]
you have to upload the mwosd hex into the minimosd first, you did this right?
Only with thw mwosd sketch , you can upload fonts from the mwosd wind0ws program

**Comment by Freakshowdevil** [comment]
Yeah I know how to do! Found the problem with vbat, on minimosd V2 it is vbat2 instead of vbat1. Everything works now I think 😆

**Comment by gc9n** [comment]
Super

**Comment by Freakshowdevil** [comment]
Now with vbat2 the little battery is showing and it's half at 7,66v

**Comment by gc9n** [comment]
Show me some pics, id like to see!come on

**Comment by Freakshowdevil** [comment]
![20170101_130651](https://cloud.githubusercontent.com/assets/21226587/21581124/373fe932-d023-11e6-9b39-00bab7a089c5.jpg)

Micro minimosd V2

**Comment by Freakshowdevil** [comment]
![20170101_130919](https://cloud.githubusercontent.com/assets/21226587/21581136/860ec1b4-d023-11e6-8532-6b441fee182a.jpg)

**Comment by Freakshowdevil** [comment]
I'm still having this F..ing heat problem.  hmmm maybe that's normal due to we are using a linear regulator. At full battery the voltage drop over the regulator is 3.4volts and the module is pulling say minimum 300mA, so 1W in heat that's going to be transferred to the board and in my case the sma connector. And the L4941 DPAK has a thermal resistance of 100C/W so it's not wonder that the connector gets hot :)

**Comment by brkdwn** [comment]
@Freakshowdevil is that the split diversity version ?

**Comment by Freakshowdevil** [comment]
Yes that's the split version but didn't cut any trace, you see the two white cables that's video. I just removed the pin and soldered a cable between pin hole (video out on module) to osd video in. And then a cable from osd video out with a pin in the other end that you put in the goggles pin hole.

**Comment by brkdwn** [comment]
Oh I see now ! Thx for the tip !
