### ISSUE TITLE
Question V2 vs. V1

### ISSUE THREAD

**Issue by 19Gerhard85** [gc9n/rx5808-Diversity-RealAcc-Compatible#12]
Hi,

can I use V2 on the Realacc module without OSD or should I use V1?

Since the release of V1 there were some commits, will there are new releases or is it safe to use the version from the master (usage without OSD)?

Greets and keep up your awesome work!

**Comment by gc9n** [comment]
hello
You can use V2 , all the changes from V1 included in V2 , When you upload V2 close the OSD in menu

**Comment by 19Gerhard85** [comment]
Thanks! Which menu do you mean?

**Comment by gc9n** [comment]
the main
upload and you will see

**Comment by 19Gerhard85** [comment]
Strange, I tried both (direct ZIP download from the repository and the release ZIP file) but I can't see any OSD options. I used Arduino 1.6.8 to open the file rx5808-pro-diversityGc9n.ino if that helps?

**Comment by gc9n** [comment]
whats your last selection in main menu SECOND page?
is it FIND MODEL?
Before that is OSD: ON
if you toggle its going to be OSD: OFF  and you are done

**Comment by 19Gerhard85** [comment]
Finally ;) Downloaded directly from master brought me to FIND MODEL.

Thanks!
