### ISSUE TITLE
Split Receiver OSD using the cable.

### ISSUE THREAD

**Issue by CptSplard** [gc9n/rx5808-Diversity-RealAcc-Compatible#15]
Hi
Thanks for the work on this, I had your FW running on my Realaccs and it was great!
I've now got a Hukiya and am investigating compatibility, but it looks like it should be good if I can figure out the joystick inputs.
I was wondering about the OSD. On a split receiver version could you hijack the video signal from the remote receiver at the wire connecting the 2, instead of modifying the receiver it's self? If you could force it to use the 2nd rx while ever there was a menu displayed there'd be no need to hack traces or cut pins and the extra power needed could be taken from closer to the lipo.

Cheers
Dean

**Comment by gc9n** [comment]
unfortunately this cant be done
