### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by andmiller** [gc9n/rx5808-Diversity-RealAcc-Compatible#4]
Is there any documentation we can add on new feature usage, module modification to use Fatshark buttons? Great work.

**Comment by gc9n** [comment]
i am working on it , i just thinking if i will make them work only in one direction , this requires only one wire to solder, So if you push up or down in fatsharks button will go only up infinity , but if you want up down direction you have to solder 3 wires . and you have also the problem that you have to go 8 times up and 8 times down.

**Comment by andmiller** [comment]
Up/Down would be better I think because you'd be able to count the channel numbers by button pushes like you can do currently with the stock modules.
