### ISSUE TITLE
Question: Realaac RX5808 Pro compatible ?

### ISSUE THREAD

**Issue by robert-hoffmann** [gc9n/rx5808-Diversity-RealAcc-Compatible#5]
Hey great mod !

Does this work with the split version ?
http://www.banggood.com/Realacc-RX5808-Open-Source-5_8G-40CH-Split-Receiver-with-OLED-Special-for-Fatshark-Goggles-p-1068207.html

....asking cause i already burned one flashing the latest LaForge formware on it :-)

**Comment by gc9n** [comment]
Ofcourse it does , its identical module , you have to find the corresponding pins from it

**Comment by robert-hoffmann** [comment]
Cool, might make this my winter project then ;-)
