### ISSUE TITLE
Separate battery needed ?

### ISSUE THREAD

**Issue by robert-hoffmann** [gc9n/rx5808-Diversity-RealAcc-Compatible#7]
I couldn't quite tell from the tutorial on OscarLiangs site if you need a separate battery ..it says the internal regulator is not enough (_We have to power both the MinimOSD + diversity module with a separate power source_).

From the schema it seems like it's just piggy-backing off the power from the ventilator and using the same battery as the goggle uses (just splitting the power off the balance lead into Y between the ventilator, and the module) ..is this right ?

**Comment by gc9n** [comment]
Exactly . the same battery , deferent path.
The 5V that comes from the goggles into the module are < 400mha propably the internal regulator used elsewhere  also.
So the battery its  the same , but we use a defernt regulator to power up the module+osd.

**Comment by robert-hoffmann** [comment]
Thanks
