### ISSUE TITLE
tantalum capacitor

### ISSUE THREAD

**Issue by Freakshowdevil** [gc9n/rx5808-Diversity-RealAcc-Compatible#8]
Shouldn't the tantalum capacitor be solder to output and ground, not input and ground as you did. The document on L4941BDT
[l4941-973941.pdf](https://github.com/gc9n/rx5808-Diversity-RealAcc-Compatible/files/664876/l4941-973941.pdf)
What I can see tantalum should be solder to output

**Comment by gc9n** [comment]
You can do it like this yes, i made the oposite because i saw a finished circuit with this regulator and it was like i did it. But you can do it like datasheet says

**Comment by Freakshowdevil** [comment]
Okey
Do you know what size on the ceramic capacitor you used, does it matter? I have a 4.7 microF tantalum and 22 nanoF ceramic or 2.2microF ceramic, which ceramic should I use?

**Comment by gc9n** [comment]
i dont really know what are the specs from the Ceramic , i know that the ceramic can handle lots of volts.
so i just picked the right size (physical dimensions)  for me. 
pick the one that can handle the most

**Comment by gc9n** [comment]
I am also working on the cables, i made it as clear as possible, the osd will be plug in and out for firmware updates, i will report soon with pics

**Comment by robert-hoffmann** [comment]
the datasheet says 1 ceramic 0.1µf on the in pin & 1 electrolyte 22µf on the out pin

**Comment by gc9n** [comment]
no problem , 
i just followed this circuit.
https://static.rcgroups.net/forums/attachments/1/7/2/2/3/6/a4459750-142-IMG_6203.jpg
as you can see the input is not a tantalum

**Comment by Freakshowdevil** [comment]
On that picture the tantalum is on the input pin, both regulators are connected to it. Data sheet says tantalum on output pin so I did it that way but  My sma connector is getting really hot like really hot, so I desoldered the regulator and restored the original 5v from goggles and the heat is gone. Maybe the tantalum should be on input pin?

**Comment by robert-hoffmann** [comment]
@Freakshowdevil what do you mean your SMA connector is getting hot ? How did you power it ?

**Comment by Freakshowdevil** [comment]
The sma connector on the module is getting hot, barely touchable. I am powering it with L4941BDT same as gc9n.

**Comment by gc9n** [comment]
you open the goggles and you replace the reg inside?

**Comment by gc9n** [comment]
What goggles do you have and what is the reg inside them?

**Comment by Freakshowdevil** [comment]
No, I moded exactly as u did, using a L4941BDT on the realacc module. Dominator HD v2 never opened it up so can't say what regulator is inside.
When I discovered that the sma was burning hot I striped all mods (L4941BDT and osd) and restored realacc to original.

**Comment by Freakshowdevil** [comment]
By sma connector I mean antenna connector

**Comment by gc9n** [comment]
Now i get it, no mine is cold, ambient temp, both sma.lets take it from start ,
what baytery did you use?
Did you connected to goggles?
Did you cut the vcc pin?
Any short circuits?

**Comment by Freakshowdevil** [comment]
Using standard battery, Vcc pin cut, did exactly as you expect that my Realacc is the split version and tantalum on output pin. No pictures, the realacc is restored to original and now it's not hot anymore, will do the mod again starting with the regulator and tantalum on input pin instead to see if that makes any difference. Maybe one of my cap was too small, should be nice to know the size of your cap (the ceramic)

**Comment by gc9n** [comment]
dont worry about the ceramic. the other is important.

**Comment by Freakshowdevil** [comment]
Maybe it is potential different on the negative side that is the problem. My guess is that the problem lays with the caps but can't get my head around why only that long SMA "antenna" connector got heated up and nothing else, but potential different can do that hmmmmm.  Will do some more testing after Xmas.

**Comment by Freakshowdevil** [comment]
A side note on OSD, rssi was visual on OSD but not the battery voltage and the fatshark buttons didn't work either. Maybe I did some thing wrong when setting minimosd up, following oscarliangs tutorial.

**Comment by Freakshowdevil** [comment]
![fatshark-fpv-goggles-realacc-osd-support-minimosd-diy-mod-connection-1024x768](https://cloud.githubusercontent.com/assets/21226587/21442414/0bc66f2e-c89e-11e6-9187-35c1c5418d19.jpg)
![fatshark-fpv-goggles-realacc-osd-support-minimosd-diy-mod-2-1](https://cloud.githubusercontent.com/assets/21226587/21442418/12f9b954-c89e-11e6-92fa-f4397b8faca9.jpg)
Your cable schematic and the pic on how you did it, pins on minimosd are not same!! Maybe it's why mine didn't work properly, I followed the schematic. What I can see is that on the schematic you're using small pad to the left of the 5v pad but on the pic on how you did it you're using the small pad where the 0 mark is on the atmega chip

**Comment by gc9n** [comment]
YES You are correct 
i made this mistake
![realacc - minimosd mod](https://cloud.githubusercontent.com/assets/3635266/21443417/b41e7676-c8ad-11e6-9e32-a64302577fd6.jpg)

![img_0243](https://cloud.githubusercontent.com/assets/3635266/21443356/36812524-c8ad-11e6-92c8-168a67f18e8d.JPG)

**Comment by gc9n** [comment]
This mistake, is the reason for Buttons response from fatsharks, and Battery feedback.

**Comment by robert-hoffmann** [comment]
Nice clean cabling of the minim there :-)

**Comment by Freakshowdevil** [comment]
Nope still no battery indication on OSD and Fatshark buttons don't work. RSSI works and the heat is gone, did put a bigger cap. 
![20161228_101412](https://cloud.githubusercontent.com/assets/21226587/21518401/79256e16-cce6-11e6-8729-33119025548c.jpg)

**Comment by gc9n** [comment]
the connections  are correct 
the software is the latest? for both module and osd?

**Comment by gc9n** [comment]
the rssi you is changing values (is alive?)

**Comment by Freakshowdevil** [comment]
Yeah everything downloaded today, yes rssi is changing value when I hold my hand in front of the antenna. No battery goggles showing up on OSD like in your video.

**Comment by gc9n** [comment]
can you measure voltage in batt1  pin and ground?

**Comment by Freakshowdevil** [comment]
7.66V batt1 and ground

**Comment by gc9n** [comment]
if i told you that i downloaded the hex files.
and it was not working to me either!!, buttons and rssi 

i uploaded a wrong version of OSD..  HOLD ON....

**Comment by gc9n** [comment]
ok
i re upload the final version, please check now 
https://github.com/gc9n/rx5808-Diversity-RealAcc-Compatible/blob/master/PolyPhemus.ino.hex

**Comment by Freakshowdevil** [comment]
No problem mate, shit happens 😂 
I will try in a bit

**Comment by Freakshowdevil** [comment]
Rssi, fatshark buttons and battery osd works like a charm mate. Great work

**Comment by gc9n** [comment]
ahhhh i am happier from you!

**Comment by Freakshowdevil** [comment]
Only one thing with osd that I noticed was that not all of the text in under menu's don't appear as they do on the oled

**Comment by gc9n** [comment]
I know . I didnt add the find model yet!

**Comment by gc9n** [comment]
now make a review!
